management:
  security:
    enabled: false
server:
  port: ${PORT:8090}
  
spring:
  h2:
    console:
      enabled: true
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:moviedb
    username: sa
    password: null
    